// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRgtLB7Oy6ZgLXGAw1Fo8HTzDp7Mz4TVQ',
    appId: '1:407879300327:web:3e69629fe27c54b12f9e42',
    messagingSenderId: '407879300327',
    projectId: 'stockniscala',
    authDomain: 'stockniscala.firebaseapp.com',
    storageBucket: 'stockniscala.appspot.com',
    measurementId: 'G-NZ0Y6TMW54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2B9ZHQ2l9w5POtGlTfyRQsSVOPFn3hM',
    appId: '1:407879300327:android:8b8d78dc29b708b72f9e42',
    messagingSenderId: '407879300327',
    projectId: 'stockniscala',
    storageBucket: 'stockniscala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1j8dBO_pHIaRcoeAq3Y0D4-VUGFBLKAI',
    appId: '1:407879300327:ios:f2114db3a8abc3cb2f9e42',
    messagingSenderId: '407879300327',
    projectId: 'stockniscala',
    storageBucket: 'stockniscala.appspot.com',
    iosClientId: '407879300327-pqfb59enfg9m2cr979qbm9c7sm017lhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockniscala',
  );
}
